USE [master]
GO

CREATE DATABASE [crudproduto]
 
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [crudproduto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [crudproduto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [crudproduto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [crudproduto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [crudproduto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [crudproduto] SET ARITHABORT OFF 
GO

ALTER DATABASE [crudproduto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [crudproduto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [crudproduto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [crudproduto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [crudproduto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [crudproduto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [crudproduto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [crudproduto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [crudproduto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [crudproduto] SET  ENABLE_BROKER 
GO

ALTER DATABASE [crudproduto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [crudproduto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [crudproduto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [crudproduto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [crudproduto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [crudproduto] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [crudproduto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [crudproduto] SET RECOVERY FULL 
GO

ALTER DATABASE [crudproduto] SET  MULTI_USER 
GO

ALTER DATABASE [crudproduto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [crudproduto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [crudproduto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [crudproduto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [crudproduto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [crudproduto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [crudproduto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [crudproduto] SET  READ_WRITE 
GO

USE crudproduto
GO


CREATE TABLE [dbo].[Produtos](
	[Id] [uniqueidentifier] NOT NULL,
	[Nome] [nvarchar](150) NOT NULL,
	[Valor] [decimal](19, 2) NOT NULL,
	[Imagem] [nvarchar](max) NULL,
	[DataCriacao] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Produtos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO