version: "3"
services:
    crud-produto-db:
        image: "mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04"
        ports:
            - "1434:1433"
        volumes: 
            - sqlsystem:/var/opt/mssql/
            - sqldata:/var/opt/sqlserver/data
            - sqllog:/var/opt/sqlserver/log
            - sqlbackup:/var/opt/sqlserver/backup
        environment:
            SA_PASSWORD: "dev@1234"
            ACCEPT_EULA: "Y"
    crud-produto-api:
        build: ./backend/
        ports: 
            - "8081:80"
        depends_on: 
            - crud-produto-db
    crud-produto-web:
        build: ./web-app
        ports: 
            - "8080:3000"
        depends_on: 
            - crud-produto-db
            - crud-produto-api
        environment: 
            - NODE_ENV=development
            - "REACT_APP_BASE_URL=http://localhost:8081"
    
volumes:
    sqlsystem:
    sqldata:
    sqllog:
    sqlbackup: